name: tfsec
on:
  pull_request:
  workflow_dispatch: 
jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          soft_fail: true
          working_directory: ./s3
          additional_args: --concise-output
